name: CI Admin Panrl to server
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-admin:
    runs-on: ubuntu-latest

    steps:
      - name: starting
        run: echo 'Start deploying!'

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: '|1|zO9SL42ViyZHQAYXGQZ7Ms7hKEk=|osdNL7OSkatSNYNUqPNa6mqdZDU='

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: git pull
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          command: |
            cd /var/www/www-root/data/www/admin.arhiterm.by/admin/admin-panel
            git pull
      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:/var/www/www-root/data/www/admin.arhiterm.by/admin/test/
