name: CI Admin Panrl to server
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-admin:
    runs-on: ubuntu-latest

    steps:
      - name: starting
      - run: echo 'Start deploying!'

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Deploy with rsync
        run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/zellwk/zellwk.com/dist/
